### ISSUE TITLE
Package is not being found by OpcUaBackend

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/open62541-interface#2]
If I install this package in my local setup (all ChimeraTK is being installed into some common location somewhere in my home directory, no ChimeraTK packages are available through the system), then try to build a depending package (DeviceAccess-OpcUaBackend), the open62541 stack is not being found correctly. It does not print any error or warning or even any message at all when running cmake of the backend about finding or not finding the stack. During compilation, it fails because it does not find the header file.

From a ChimeraTK perspective, the cmake packaging mechanism used in this package is non-standard. The very idea of this interface package as part of ChimeraTK would be to make an easy interface between open62541 and ChimeraTK. Hence I suggest to change the packaging mechanism to the same as used by all other ChimeraTK packages. Only this guarantees that the user does not have to learn special tricks for each package and instead can just use any package right away (once the general principle of the ChimeraTK packages is known).

**Comment by zenker** [comment]
I merged the correct version of the DeviceAccess-OPC-UA to the master branch. Now for me the situation is as following:
- DebianPackagingScripts work and dependencies are resolved when building the debian packages open62541, chimeratk-deviceaccess-opc-ua-backend, chimeratk-controlsystemadapter-opcuaadapter
- local build with only -DCMAKE_MODULE_PATH is not working because I don't provide Findopen62541.cmake
- local build with additional -DCMAKE_INSTALL_PREFIX (should be the same for all packages build) works and the open62541Config.cmake is found
I don't really like to define all the includes/libraries and so on again just to generate the Findopen62541. In addition it appears to me using the open62541Config.cmake is the prefered way of searching for a project (see also https://cmake.org/cmake/help/latest/command/find_package.html Config Mode).
What do you think @mhier?

**Comment by mhier** [comment]
it seems to work now, thanks
